name 'poise'
source_url 'https://github.com/chef-cookbooks/poise'
issues_url 'https://github.com/chef-cookbooks/poise/issues'
maintainer 'John B'
maintainer_email 'johnb@chef.io'
license 'Apache 2.0'
version '2.7.0'


supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
