driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: installation_binary-222
    run_list:
      - recipe[etcd_test::installation_binary]
    attributes:
      etcd:
        version: '2.2.2'

  - name: service-execute
    run_list:
      - recipe[etcd_test::service_execute]

  - name: service-execute-multi
    run_list:
      - recipe[etcd_test::service_execute_multi]

  - name: service-systemd
    includes: [
    'debian-8',
    'centos-7',
    'fedora-21',
    'ubuntu-15.10'
    ]
    run_list:
      - recipe[etcd_test::service_systemd]

  - name: service-systemd-multi
    includes: [
    'debian-8',
    'centos-7',
    'fedora-21',
    'ubuntu-15.10'
    ]
    run_list:
      - recipe[etcd_test::service_systemd_multi]

  - name: service-upstart
    includes: [
    'ubuntu-14.04'
    ]
    run_list:
      - recipe[etcd_test::service_upstart]

  - name: service-upstart-multi
    includes: [
    'ubuntu-14.04'
    ]
    run_list:
      - recipe[etcd_test::service_upstart_multi]

  - name: service-sysvinit
    includes: [
    'debian-7',
    'centos-5',
    'centos-6',
    'ubuntu-12.04'
    ]
    run_list:
      - recipe[etcd_test::service_sysvinit]

  - name: service-sysvinit-multi
    includes: [
    'debian-7',
    'centos-5',
    'centos-6',
    'ubuntu-12.04'
    ]
    run_list:
      - recipe[etcd_test::service_sysvinit_multi]

  - name: keys
    includes: [
      'centos-7'
    ]
    run_list:
      - recipe[etcd_test::keys]

  - name: auto
    run_list:
      - recipe[etcd_test::auto]
