name 'poise-service'
source_url 'https://github.com/chef-cookbooks/poise-service'
issues_url 'https://github.com/chef-cookbooks/poise-service/issues'
maintainer 'John B'
maintainer_email 'johnb@chef.io'
license 'Apache 2.0'
version '1.3.1'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
