name 'confd'
source_url 'https://github.com/chef-cookbooks/confd'
issues_url 'https://github.com/chef-cookbooks/confd/issues'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures confd.'
long_description 'Application cookbook which installs and configures confd.'
version '1.1.2'

depends 'poise', '= 2.7.0'
depends 'poise-service', '= 1.3.1'
depends 'rc', '=1.6.4'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'

