name 'rc'
source_url 'https://github.com/chef-cookbooks/rc'
issues_url 'https://github.com/chef-cookbooks/rc/issues'
maintainer 'John B'
maintainer_email 'johnb@chef.io'
license 'Apache 2.0'
version '1.6.4'

depends 'poise', '>= 2.2'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
